'use strict';
const prisma = require('../lib/prisma');
const analytics = require('./analyticsService');
const { round1 } = require('../utils/macroUtils');

function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

/** Builds the data + HTML for one user's daily report. This is the single
 * source both GET /reports/daily and the email scheduler render from, so
 * the emailed report and the in-app/downloaded one are always identical. */
async function buildDailyReport(userId, dateStr) {
  const [profile, goals, { totals, meals }, weight] = await Promise.all([
    prisma.profile.findUnique({ where: { userId } }),
    prisma.nutritionGoal.findUnique({ where: { userId } }),
    analytics.dayTotals(userId, dateStr),
    prisma.weightLog.findUnique({ where: { userId_date: { userId, date: new Date(dateStr) } } }).catch(() => null),
  ]);
  const latestAiRec = await prisma.aiRecommendation.findFirst({
    where: { userId, kind: 'daily_analysis', requestCtx: { path: ['date'], equals: dateStr } },
    orderBy: { createdAt: 'desc' },
  });

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Nourish report — ${dateStr}</title>
<style>body{font-family:-apple-system,Inter,sans-serif;max-width:640px;margin:30px auto;color:#211D1A;padding:0 20px}
h1{font-family:Georgia,serif} table{width:100%;border-collapse:collapse}
.badge{background:#F5E6C8;color:#C98A2C;padding:2px 8px;border-radius:20px;font-size:11px}</style></head><body>
<h1>Your daily nutrition report</h1>
<p style="color:#888">${esc(new Date(dateStr + 'T00:00:00Z').toDateString())} · ${esc(profile ? profile.name : '')}</p>
<h2>Summary</h2>
<table>
${row('Calories', totals.calories, goals ? goals.calories : null, 'kcal')}
${row('Protein', totals.proteinG, goals ? goals.proteinG : null, 'g')}
${row('Carbohydrates', totals.carbsG, goals ? goals.carbsG : null, 'g')}
${row('Fat', totals.fatG, goals ? goals.fatG : null, 'g')}
${row('Fibre', totals.fibreG, goals ? goals.fibreG : null, 'g')}
</table>
<h2>Meals logged (${meals.length})</h2>
<ul>${meals
    .map((m) => {
      const t = analytics.mealTotals(m);
      return `<li><b>${esc(m.mealType)}</b> (${esc(m.time || '')}) — ${m.items.map((i) => esc(i.name)).join(', ')} — ${Math.round(t.calories)} kcal <span class="badge">${esc(m.source)}</span></li>`;
    })
    .join('')}</ul>
${weight ? `<p><b>Weight logged:</b> ${weight.weightKg} kg</p>` : ''}
${
  latestAiRec
    ? `<h2>AI analysis</h2><ul>${(latestAiRec.response.observations || []).map((o) => `<li>${esc(o)}</li>`).join('')}</ul>
<h2>Recommendations for tomorrow</h2><ul>${(latestAiRec.response.recommendations || []).map((r) => `<li>${esc(r)}</li>`).join('')}</ul>`
    : ''
}
<p style="color:#888;font-size:12px;margin-top:30px">AI-estimated nutrition, not medical advice. Generated by Nourish.</p>
</body></html>`;

  return { dateStr, totals, goals, meals, weight, html };
}

async function buildWeeklyReport(userId, endDateStr, startDateStr) {
  const [profile, goals, stats] = await Promise.all([
    prisma.profile.findUnique({ where: { userId } }),
    prisma.nutritionGoal.findUnique({ where: { userId } }),
    analytics.rangeStats(userId, startDateStr, endDateStr),
  ]);

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Weekly report</title>
<style>body{font-family:-apple-system,Inter,sans-serif;max-width:640px;margin:30px auto;color:#211D1A;padding:0 20px} h1{font-family:Georgia,serif}</style>
</head><body>
<h1>Your weekly nutrition report</h1>
<p style="color:#888">${esc(startDateStr)} – ${esc(endDateStr)} · ${esc(profile ? profile.name : '')}</p>
<h2>Averages</h2>
<ul>
<li>Calories: ${Math.round(stats.avg.calories)} kcal/day (target ${goals ? goals.calories : '—'})</li>
<li>Protein: ${round1(stats.avg.proteinG)}g/day (target ${goals ? goals.proteinG : '—'})</li>
<li>Carbohydrates: ${round1(stats.avg.carbsG)}g/day</li>
<li>Fat: ${round1(stats.avg.fatG)}g/day</li>
<li>Fibre: ${round1(stats.avg.fibreG)}g/day</li>
</ul>
<h2>Consistency</h2><p>Logged ${stats.loggedDays} of ${stats.totalDays} days.</p>
<h2>Most frequent foods</h2>
<ul>${stats.topFoods.map((f) => `<li>${esc(f.name)} — ${f.count}×</li>`).join('') || '<li>Not enough data</li>'}</ul>
<p style="color:#888;font-size:12px;margin-top:30px">AI-estimated nutrition, not medical advice. Generated by Nourish.</p>
</body></html>`;

  return { startDateStr, endDateStr, stats, html };
}

function row(label, value, target, unit) {
  return `<tr><td style="padding:6px 0;border-bottom:1px solid #eee">${label}</td>
<td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right"><b>${round1(value)}${unit}</b></td>
<td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;color:#888">${target != null ? `/ ${target}${unit}` : ''}</td></tr>`;
}

module.exports = { buildDailyReport, buildWeeklyReport };
